const mongoose = require("mongoose");
const AutoIncrement = require("mongoose-sequence")(mongoose);

const ElasticQtySchema = new mongoose.Schema(
  {
    elastic:  { type: mongoose.Types.ObjectId, ref: "Elastic", required: true },
    quantity: { type: Number, default: 0 },
  },
  { _id: false }
);

/**
 * 🔹 Fingerprint sub-schema — full audit timeline (mirrors
 * Order.fingerprints). Sits alongside the per-stage User refs
 * (weavingBy, finishingBy, …); generated by utils/fingerprint.js.
 */
const FingerprintSchema = new mongoose.Schema(
  {
    code:    { type: String, required: true },
    label:   { type: String, required: true },
    hash:    { type: String, required: true },
    shortId: { type: String, required: true },
    at:      { type: Date,   required: true, default: Date.now },
    actor:   {
      type:    mongoose.Schema.Types.Mixed,
      default: { id: "system", name: "System", role: "system" },
    },
    meta:    { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  { _id: false }
);

const JobOrderSchema = new mongoose.Schema(
  {
    date: { type: Date, required: true },
    order: { type: mongoose.Types.ObjectId, ref: "Order", required: true, index: true },
    customer: { type: mongoose.Types.ObjectId, ref: "Customer", required: true },
    jobOrderNo: { type: Number, immutable: true },

    status: {
      type: String,
      enum: ["preparatory", "weaving", "finishing", "checking", "packing", "completed", "cancelled"],
      default: "preparatory",
    },

    // Whether this job is woven in-house or sent to a subcontractor.
    // Drives the framing of the Material Requirement Program (MRP)
    // sheet — an outsourced job's MRP carries a vendor section. Purely
    // informational for now; stock deduction is unchanged.
    productionMode: {
      type: String,
      enum: ["in_house", "outsource"],
      default: "in_house",
    },
    // Free-text vendor/subcontractor name; only meaningful when
    // productionMode === "outsource".
    outsourceVendor: { type: String, default: "" },

    elastics:        { type: [ElasticQtySchema], default: [] },
    producedElastic: { type: [ElasticQtySchema], default: [] },
    packedElastic:   { type: [ElasticQtySchema], default: [] },
    wastageElastic:  { type: [ElasticQtySchema], default: [] },

    warping:  { type: mongoose.Types.ObjectId, ref: "Warping" },
    covering: { type: mongoose.Types.ObjectId, ref: "Covering" },
    machine:  { type: mongoose.Types.ObjectId, ref: "Machine" },

    shiftDetails:   [{ type: mongoose.Types.ObjectId, ref: "ShiftDetail" }],
    wastages:       [{ type: mongoose.Types.ObjectId, ref: "Wastage" }],
    packingDetails: [{ type: mongoose.Types.ObjectId, ref: "Packing" }],

    // Per-stage fingerprints — set explicitly in each route handler
    weavingBy:   { type: mongoose.Types.ObjectId, ref: "User" },
    weavingAt:   { type: Date },
    finishingBy: { type: mongoose.Types.ObjectId, ref: "User" },
    finishingAt: { type: Date },
    checkingBy:  { type: mongoose.Types.ObjectId, ref: "User" },
    checkingAt:  { type: Date },
    packingBy:   { type: mongoose.Types.ObjectId, ref: "User" },
    packingAt:   { type: Date },
    completedBy: { type: mongoose.Types.ObjectId, ref: "User" },
    completedAt: { type: Date },
    cancelledBy: { type: mongoose.Types.ObjectId, ref: "User" },
    cancelledAt: { type: Date },

    // 🪪 Full audit timeline — see FingerprintSchema above.
    fingerprints: {
      type:    [FingerprintSchema],
      default: [],
    },
  },
  { timestamps: true }
);

JobOrderSchema.plugin(AutoIncrement, { inc_field: "jobOrderNo" });

module.exports = mongoose.model("JobOrder", JobOrderSchema);
