const mongoose = require("mongoose");
const AutoIncrement = require("mongoose-sequence")(mongoose);

const ElasticQtySchema = new mongoose.Schema(
  {
    elastic:  { type: mongoose.Types.ObjectId, ref: "Elastic", required: true },
    quantity: { type: Number, default: 0 },
  },
  { _id: false }
);

/**
 * 🔹 Fingerprint sub-schema — full audit timeline (mirrors
 * Order.fingerprints). Sits alongside the per-stage User refs
 * (weavingBy, finishingBy, …); generated by utils/fingerprint.js.
 */
const FingerprintSchema = new mongoose.Schema(
  {
    code:    { type: String, required: true },
    label:   { type: String, required: true },
    hash:    { type: String, required: true },
    shortId: { type: String, required: true },
    at:      { type: Date,   required: true, default: Date.now },
    actor:   {
      type:    mongoose.Schema.Types.Mixed,
      default: { id: "system", name: "System", role: "system" },
    },
    meta:    { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  { _id: false }
);

const JobOrderSchema = new mongoose.Schema(
  {
    date: { type: Date, required: true },
    order: { type: mongoose.Types.ObjectId, ref: "Order", required: true, index: true },
    customer: { type: mongoose.Types.ObjectId, ref: "Customer", required: true },
    jobOrderNo: { type: Number, immutable: true },

    status: {
      type: String,
      enum: ["preparatory", "weaving", "finishing", "checking", "packing", "completed", "cancelled"],
      default: "preparatory",
    },

    // Whether this job is woven in-house or sent to a subcontractor.
    // Drives the framing of the Material Requirement Program (MRP)
    // sheet — an outsourced job's MRP carries a vendor section. Purely
    // informational for now; stock deduction is unchanged.
    productionMode: {
      type: String,
      enum: ["in_house", "outsource"],
      default: "in_house",
    },
    // Free-text vendor/subcontractor name; only meaningful when
    // productionMode === "outsource".
    outsourceVendor: { type: String, default: "" },

    // ── Outsourced job-work record ────────────────────────────────
    // An outsourced job produces no shifts here, so this IS its
    // production record: what went to the vendor, what came back, the
    // yield, and when. The job cannot move to `finishing` until the
    // reconciliation fields are filled — see utils/outsourcingRecord.js,
    // which owns that rule for both the gate and the UI.
    //
    // Nothing here is `required` at the schema level: the record is
    // filled in progressively as the consignment goes out and comes
    // back, and completeness is enforced at the finishing gate instead.
    outsourcing: {
      // The reconciliation set — required to reach `finishing`.
      qtySentMeters:     { type: Number, default: null },
      qtyReceivedMeters: { type: Number, default: null },
      // Entered by the planner, not derived: the vendor's own figure is
      // what gets agreed and paid against. The derived yield is shown
      // beside it so a disagreement is visible rather than silent.
      efficiencyPct:     { type: Number, default: null },
      actualReturnDate:  { type: Date,   default: null },
      notes:             { type: String, default: "" },

      // Optional planning / costing / compliance detail.
      dispatchDate:       { type: Date,   default: null },
      expectedReturnDate: { type: Date,   default: null },
      rejectedMeters:     { type: Number, default: null },
      ratePerMeter:       { type: Number, default: null },
      outwardChallanNo:   { type: String, default: "" },
      inwardChallanNo:    { type: String, default: "" },

      // Who last wrote the record, for the audit trail.
      recordedBy: { type: mongoose.Types.ObjectId, ref: "User", default: null },
      recordedAt: { type: Date, default: null },
    },

    // ── Actual conversion cost, when it differs from the rate card ──
    // Finishing, checking and packing are costed from the ₹/meter rate
    // card in CostSettings. A job that actually cost something else
    // carries the real figure here, in RUPEES for the whole job, and it
    // wins over the rate.
    //
    // null means "no override" — deliberately distinct from 0, which is
    // a planner saying this job cost nothing to finish. Defaulting these
    // to 0 would have made every job an override of zero and quietly
    // zeroed the rate card for the entire factory.
    costOverrides: {
      finishing: { type: Number, default: null, min: 0 },
      checking:  { type: Number, default: null, min: 0 },
      packing:   { type: Number, default: null, min: 0 },
      overhead:  { type: Number, default: null, min: 0 },
      notes:     { type: String, default: "" },
      recordedBy: { type: mongoose.Types.ObjectId, ref: "User", default: null },
      recordedAt: { type: Date, default: null },
    },

    elastics:        { type: [ElasticQtySchema], default: [] },
    producedElastic: { type: [ElasticQtySchema], default: [] },
    packedElastic:   { type: [ElasticQtySchema], default: [] },
    wastageElastic:  { type: [ElasticQtySchema], default: [] },

    warping:  { type: mongoose.Types.ObjectId, ref: "Warping" },
    covering: { type: mongoose.Types.ObjectId, ref: "Covering" },
    machine:  { type: mongoose.Types.ObjectId, ref: "Machine" },

    shiftDetails:   [{ type: mongoose.Types.ObjectId, ref: "ShiftDetail" }],
    wastages:       [{ type: mongoose.Types.ObjectId, ref: "Wastage" }],
    packingDetails: [{ type: mongoose.Types.ObjectId, ref: "Packing" }],

    // Per-stage fingerprints — set explicitly in each route handler
    weavingBy:   { type: mongoose.Types.ObjectId, ref: "User" },
    weavingAt:   { type: Date },
    finishingBy: { type: mongoose.Types.ObjectId, ref: "User" },
    finishingAt: { type: Date },
    checkingBy:  { type: mongoose.Types.ObjectId, ref: "User" },
    checkingAt:  { type: Date },
    packingBy:   { type: mongoose.Types.ObjectId, ref: "User" },
    packingAt:   { type: Date },
    completedBy: { type: mongoose.Types.ObjectId, ref: "User" },
    completedAt: { type: Date },
    cancelledBy: { type: mongoose.Types.ObjectId, ref: "User" },
    cancelledAt: { type: Date },

    // 🪪 Full audit timeline — see FingerprintSchema above.
    fingerprints: {
      type:    [FingerprintSchema],
      default: [],
    },
  },
  { timestamps: true }
);

JobOrderSchema.plugin(AutoIncrement, { inc_field: "jobOrderNo" });

// The elastic detail page: every job that made one product, newest
// first. Multikey on the elastics array, so a job is indexed once per
// product it carries. Without it the list is a full collection scan and
// then an in-memory sort — see the note on OrderSchema's indexes for why
// that fails outright rather than merely slowly.
JobOrderSchema.index({ "elastics.elastic": 1, date: -1 });
// One customer's jobs, newest first — the complaint form's job picker,
// and the exposure lookup behind the blast-radius trace.
JobOrderSchema.index({ customer: 1, createdAt: -1 });

module.exports = mongoose.model("JobOrder", JobOrderSchema);
