const mongoose = require("mongoose");
const AutoIncrement = require("mongoose-sequence")(mongoose);

/**
 * 🔹 Reusable Elastic Quantity Sub-Schema
 */
const ElasticQtySchema = new mongoose.Schema(
  {
    elastic: {
      type: mongoose.Types.ObjectId,
      ref: "Elastic",
      required: true,
    },
    quantity: {
      type: Number,
      default: 0,
    },
  },
  { _id: false }
);

/**
 * 🔹 Fingerprint sub-schema (mirrors Order.fingerprints).
 * One entry per job lifecycle event — creation, stage update,
 * completion, cancellation. Generated by utils/fingerprint.js.
 */
const FingerprintSchema = new mongoose.Schema(
  {
    code:    { type: String, required: true },
    label:   { type: String, required: true },
    hash:    { type: String, required: true },
    shortId: { type: String, required: true },
    at:      { type: Date,   required: true, default: Date.now },
    // Full actor info: { id, name, role, email? } — embedded to avoid
    // joins when rendering the timeline in the mobile app.
    actor:   {
      type:    mongoose.Schema.Types.Mixed,
      default: { id: "system", name: "System", role: "system" },
    },
    meta:    { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  { _id: false }
);

/**
 * 🧾 JOB ORDER SCHEMA
 */
const JobOrderSchema = new mongoose.Schema(
  {
    // 📅 BASIC INFO
    date: {
      type: Date,
      required: true,
    },

    // 🔗 LINK TO MAIN ORDER (IMPORTANT)
    order: {
      type: mongoose.Types.ObjectId,
      ref: "Order",
      required: true,
      index: true,
    },

    customer: {
      type: mongoose.Types.ObjectId,
      ref: "Customer",
      required: true,
    },

    // 🔢 AUTO INCREMENT
    jobOrderNo: {
      type: Number,
      immutable: true,
    },

    // 🏗 JOB STATUS (FLOW-BASED)
    status: {
      type: String,
      enum: [
        "preparatory",
        "weaving",
        "finishing",
        "checking",
        "packing",
        "completed",
        "cancelled",
      ],
      default: "preparatory",
    },

    // 🧵 PLANNED ELASTICS
    elastics: {
      type: [ElasticQtySchema],
      default: [],
    },

    // 🧵 PRODUCED ELASTICS
    producedElastic: {
      type: [ElasticQtySchema],
      default: [],
    },

    // 📦 PACKED ELASTICS
    packedElastic: {
      type: [ElasticQtySchema],
      default: [],
    },

    // ♻️ WASTAGE
    wastageElastic: {
      type: [ElasticQtySchema],
      default: [],
    },

    // 🏭 PROCESS REFERENCES
    warping: {
      type: mongoose.Types.ObjectId,
      ref: "Warping",
    },

    covering: {
      type: mongoose.Types.ObjectId,
      ref: "Covering",
    },

    machine: {
      type: mongoose.Types.ObjectId,
      ref: "Machine",
    },

    // ⏱ SHIFT-LEVEL TRACEABILITY
    shiftDetails: [
      {
        type: mongoose.Types.ObjectId,
        ref: "ShiftDetail",
      },
    ],

    // ♻️ WASTAGE LOG
    wastages: [
      {
        type: mongoose.Types.ObjectId,
        ref: "Wastage",
      },
    ],

    // 📦 PACKING DETAILS
    packingDetails: [
      {
        type: mongoose.Types.ObjectId,
        ref: "Packing",
      },
    ],

    // 🪪 Audit fingerprints — one entry per job state transition.
    // See utils/fingerprint.js for details.
    fingerprints: {
      type: [FingerprintSchema],
      default: [],
    },
  },
  { timestamps: true }
);

/**
 * 🔢 AUTO-INCREMENT JOB ORDER NO
 */
JobOrderSchema.plugin(AutoIncrement, {
  inc_field: "jobOrderNo",
});

module.exports = mongoose.model("JobOrder", JobOrderSchema);
