const mongoose = require("mongoose");
const AutoIncrement = require("mongoose-sequence")(mongoose);

/**
 * 🔹 Reusable sub-schema for Elastic quantity tracking
 */
const ElasticQtySchema = new mongoose.Schema(
  {
    elastic: {
      type: mongoose.Types.ObjectId,
      ref: "Elastic",
      required: true,
    },
    quantity: {
      type: Number,
      required: true,
      default: 0,
    },
  },
  { _id: false }
);

/**
 * 🔹 Raw material snapshot at order creation
 */
const RawMaterialRequirementSchema = new mongoose.Schema(
  {
    rawMaterial: {
      type: mongoose.Types.ObjectId,
      ref: "RawMaterial",
      required: true,
    },
    name: {
      type: String,
    },
    requiredWeight: {
      type: Number,
    },
    inStock: {
      type: Number,
    },
  },
  { _id: false }
);

/**
 * 🔹 Job reference schema
 */
const JobRefSchema = new mongoose.Schema(
  {
    job: {
      type: mongoose.Types.ObjectId,
      ref: "JobOrder",
      required: true,
    },
    no: {
      type: Number,
      required: true,
      default: 0,
    },
  },
  { _id: false }
);

/**
 * 🔹 Fingerprint sub-schema
 *
 * One entry per meaningful action against this order
 * (creation, approval, stock deduction, completion, etc.).
 * Generated by utils/fingerprint.js.
 */
const FingerprintSchema = new mongoose.Schema(
  {
    code:    { type: String, required: true },
    label:   { type: String, required: true },
    hash:    { type: String, required: true },
    shortId: { type: String, required: true },
    at:      { type: Date,   required: true, default: Date.now },
    // Full actor info: { id, name, role, email? } — embedded to avoid
    // joins when rendering the timeline in the mobile app.
    actor:   {
      type:    mongoose.Schema.Types.Mixed,
      default: { id: "system", name: "System", role: "system" },
    },
    meta:    { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  { _id: false }
);

/**
 * 🧾 ORDER SCHEMA
 */
const OrderSchema = new mongoose.Schema(
  {
    date: {
      type: Date,
      required: true,
    },

    po: {
      type: String,
      required: true,
      trim: true,
    },

    customer: {
      type: mongoose.Types.ObjectId,
      ref: "Customer",
      required: true,
    },

    supplyDate: {
      type: Date,
      required: true,
    },

    description: {
      type: String,
      default: "",
    },

    // 🧵 Elastic tracking
    elasticOrdered: {
      type: [ElasticQtySchema],
      default: [],
    },

    producedElastic: {
      type: [ElasticQtySchema],
      default: [],
    },

    packedElastic: {
      type: [ElasticQtySchema],
      default: [],
    },

    pendingElastic: {
      type: [ElasticQtySchema],
      default: [],
    },

    // 🧮 Raw material snapshot
    rawMaterialRequired: {
      type: [RawMaterialRequirementSchema],
      default: [],
    },

    // 🏭 Jobs created under this order
    jobs: {
      type: [JobRefSchema],
      default: [],
    },

    status: {
      type: String,
      enum: ["Open", "Approved","InProgress", "Completed", "Cancelled"],
      default: "Open",
    },

    // 🪪 Audit fingerprints — one entry per state transition.
    // See utils/fingerprint.js for details.
    fingerprints: {
      type: [FingerprintSchema],
      default: [],
    },

    // 🔢 Auto-generated
    orderNo: {
      type: Number,
      immutable: true,
    },
  },
  { timestamps: true }
);

/**
 * 🔢 Auto Increment Order Number
 */
OrderSchema.plugin(AutoIncrement, { inc_field: "orderNo" });

module.exports = mongoose.model("Order", OrderSchema);
