const mongoose = require("mongoose");
const AutoIncrement = require("mongoose-sequence")(mongoose);

const ElasticQtySchema = new mongoose.Schema(
  {
    elastic:  { type: mongoose.Types.ObjectId, ref: "Elastic", required: true },
    quantity: { type: Number, required: true, default: 0 },
  },
  { _id: false }
);

const RawMaterialRequirementSchema = new mongoose.Schema(
  {
    rawMaterial:    { type: mongoose.Types.ObjectId, ref: "RawMaterial", required: true },
    name:           { type: String },
    requiredWeight: { type: Number },
    inStock:        { type: Number },
  },
  { _id: false }
);

const JobRefSchema = new mongoose.Schema(
  {
    job: { type: mongoose.Types.ObjectId, ref: "JobOrder", required: true },
    no:  { type: Number, required: true, default: 0 },
  },
  { _id: false }
);

/**
 * 🔹 Fingerprint sub-schema — full audit timeline.
 * Sits alongside the per-state User refs (approvedBy, cancelledBy,
 * startedBy, completedBy). The per-state refs are the canonical
 * "who did X" pointers used by detail views; this array gives the
 * full chronological log (with hashes) used by the timeline UI.
 * Generated by utils/fingerprint.js.
 */
const FingerprintSchema = new mongoose.Schema(
  {
    code:    { type: String, required: true },
    label:   { type: String, required: true },
    hash:    { type: String, required: true },
    shortId: { type: String, required: true },
    at:      { type: Date,   required: true, default: Date.now },
    actor:   {
      type:    mongoose.Schema.Types.Mixed,
      default: { id: "system", name: "System", role: "system" },
    },
    meta:    { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  { _id: false }
);

const OrderSchema = new mongoose.Schema(
  {
    date:        { type: Date, required: true },
    po:          { type: String, required: true, trim: true },
    customer:    { type: mongoose.Types.ObjectId, ref: "Customer", required: true },
    supplyDate:  { type: Date, required: true },
    description: { type: String, default: "" },

    elasticOrdered:      { type: [ElasticQtySchema], default: [] },
    producedElastic:     { type: [ElasticQtySchema], default: [] },
    packedElastic:       { type: [ElasticQtySchema], default: [] },
    pendingElastic:      { type: [ElasticQtySchema], default: [] },
    rawMaterialRequired: { type: [RawMaterialRequirementSchema], default: [] },
    jobs:                { type: [JobRefSchema], default: [] },

    status: {
      type:    String,
      enum:    ["Open", "Approved", "InProgress", "Completed", "Cancelled", "Deleted"],
      default: "Open",
    },

    // Per-state fingerprints — set explicitly in each route handler
    approvedBy:  { type: mongoose.Types.ObjectId, ref: "User" },
    approvedAt:  { type: Date },
    cancelledBy: { type: mongoose.Types.ObjectId, ref: "User" },
    cancelledAt: { type: Date },
    startedBy:   { type: mongoose.Types.ObjectId, ref: "User" },
    startedAt:   { type: Date },
    completedBy: { type: mongoose.Types.ObjectId, ref: "User" },
    completedAt: { type: Date },
    deletedBy:   { type: mongoose.Types.ObjectId, ref: "User" },
    deletedAt:   { type: Date },
    updatedItemsAt: { type: Date },

    // 🪪 Full audit timeline — see FingerprintSchema above.
    fingerprints: {
      type:    [FingerprintSchema],
      default: [],
    },

    orderNo: { type: Number, immutable: true },
  },
  { timestamps: true }
);

OrderSchema.plugin(AutoIncrement, { inc_field: "orderNo" });

module.exports = mongoose.model("Order", OrderSchema);
