// ══════════════════════════════════════════════════════════════
//  PAYROLL MODEL
//  File: models/Payroll.js
//
//  One document per employee per month (month+year).
//  Generated by POST /api/v2/payroll/generate
//  Can be regenerated (idempotent upsert).
// ══════════════════════════════════════════════════════════════
'use strict';
const mongoose = require('mongoose');

const ShiftBreakdownSchema = new mongoose.Schema({
  shift:           String,    // DAY | NIGHT
  count:           Number,    // shifts worked
  hours:           Number,    // total hours
  grossPay:        Number,    // before deductions
}, { _id: false });

const PayrollSchema = new mongoose.Schema({
  employee:  { type: mongoose.Types.ObjectId, ref: 'Employee', required: true },
  month:     { type: Number, required: true, min: 1, max: 12 },
  year:      { type: Number, required: true },

  // ── Attendance summary ────────────────────────────────────
  totalShifts:        { type: Number, default: 0 },
  presentShifts:      { type: Number, default: 0 },
  lateShifts:         { type: Number, default: 0 },
  halfDayShifts:      { type: Number, default: 0 },
  absentShifts:       { type: Number, default: 0 },
  approvedLeaves:     { type: Number, default: 0 },   // on_leave + isApprovedLeave
  unapprovedAbsents:  { type: Number, default: 0 },   // absent without approved leave
  totalHoursWorked:   { type: Number, default: 0 },
  attendancePct:      { type: Number, default: 0 },   // 0-100

  // Shift breakdown
  dayBreakdown:   ShiftBreakdownSchema,
  nightBreakdown: ShiftBreakdownSchema,

  // ── Pay calculation ───────────────────────────────────────
  hourlyRate:     { type: Number, default: 0 },

  grossPay:       { type: Number, default: 0 },   // hours × rate before any adjustment
  lateDeductions: { type: Number, default: 0 },   // sum of late-minute penalties
  absentPenalty:  { type: Number, default: 0 },   // excess absent deductions
  otherDeductions:{ type: Number, default: 0 },

  // Rewards
  perfectAttendanceBonus: { type: Number, default: 0 },
  streakBonus:            { type: Number, default: 0 },
  noLeaveBonus:           { type: Number, default: 0 },  // never took leave all month
  otherBonus:             { type: Number, default: 0 },

  totalDeductions: { type: Number, default: 0 },
  totalBonus:      { type: Number, default: 0 },
  netPay:          { type: Number, default: 0 },

  // ── Leave quota ───────────────────────────────────────────
  leaveQuota:     { type: Number, default: 2 },
  sickQuota:      { type: Number, default: 1 },
  leavesUsed:     { type: Number, default: 0 },   // approved leaves this month
  excessAbsents:  { type: Number, default: 0 },   // unapproved beyond quota

  // ── Status ────────────────────────────────────────────────
  status: {
    type: String,
    enum: ['draft', 'finalised', 'paid'],
    default: 'draft',
  },
  generatedAt:  { type: Date, default: Date.now },
  finalisedAt:  { type: Date },
  paidAt:       { type: Date },
  notes:        { type: String, default: '' },

}, { timestamps: true });

PayrollSchema.index({ employee: 1, month: 1, year: 1 }, { unique: true });

module.exports = mongoose.model('Payroll', PayrollSchema);